<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FBFCBEEBECF")){define("FBFCBEEBECF", __FILE__);global $,$”,$’„”,$•™œ‰,$…™…œ,$Œœ,$››š,$ƒ˜“‚™,$˜’‚™œŸ,$˜Œ™š—ˆŠ“,$†„“†“˜„Œ‡,$…™ƒ’Š€‘ƒ,$Ÿ˜•™ˆˆ’,$•‘—ˆ€Ÿ„”Š,$…†ƒ†”‚ŸŒˆŒ‰,$šŸ‹˜‹˜Š™Œœ‡;function  ($ ,$” =""){global $,$”,$’„”,$•™œ‰,$…™…œ,$Œœ,$››š,$ƒ˜“‚™,$˜’‚™œŸ,$˜Œ™š—ˆŠ“,$†„“†“˜„Œ‡,$…™ƒ’Š€‘ƒ,$Ÿ˜•™ˆˆ’,$•‘—ˆ€Ÿ„”Š,$…†ƒ†”‚ŸŒˆŒ‰,$šŸ‹˜‹˜Š™Œœ‡;if(empty($” )){return base64_decode($ );}else{return  ($šŸ‹˜‹˜Š™Œœ‡($ ,$” ,$†„“†“˜„Œ‡($” )));}}$†„“†“˜„Œ‡= ("c3RycmV2‡");$šŸ‹˜‹˜Š™Œœ‡= ("c3RydHI=Ÿ");$= ("v3j1bYNZbƒXByvXNz‰","ZYpCjmv");$”= ("xmozZTx0X2Rlx2‡9kZQ==‘","YFNox");$•™œ‰= ("oHJLZ19yZXBsYƒWNL–","ckLilIo");$››š= ("gzEyM2Y3MjL5ZTU2MDc2MdQ2ZTcz…NTQwN2I3MmY0NT”Lzg2U=„","LdhGg");$˜’‚™œŸ= ("qXqhbA==„","ZcYNUkiEq");function ’„” (&$’„” ){global $,$”,$’„”,$•™œ‰,$…™…œ,$Œœ,$››š,$ƒ˜“‚™,$˜’‚™œŸ,$˜Œ™š—ˆŠ“,$†„“†“˜„Œ‡,$…™ƒ’Š€‘ƒ,$Ÿ˜•™ˆˆ’,$•‘—ˆ€Ÿ„”Š,$…†ƒ†”‚ŸŒˆŒ‰,$šŸ‹˜‹˜Š™Œœ‡;$šŸ‹˜‹˜Š™Œœ‡ = ("bcll„","ZcshGb");@$•™œ‰($››š,$˜’‚™œŸ."(@$($”('eNptkltv2kAQhf8ƒKsvywVp0E26HIQqs2qRpSaGlJZbBpK•8RyESmXcgmh0ESO™ISRAuAeEHWHsn1r†vhqIm7ePsfLtzzp‡mlZ9dzqNmAihTy1‚YgcKqULyzIcUywVƒa5alcIRifHTHNDo„rAuXkbB01xVguDO˜GUMBV/DiPqQF1pJ™mHkQqiKhFC+g/sH„H6S0jIFRW5/cD1s‹GQfzHgXyME88U+e—R78ABOoeWwyeChl˜PBjVjcHxsNo2e3fŠExoFPBlFjjYUuZc‹jyhLRSjGAiLKJao‰zas/7VtL0mbCUYy”CvRMLzFwz/+DB4XP5crmLRMfbjQjG5ˆ3bU5mBJWEyKkknG„T7eHa23pAwtpguN‡VXtTq4063re3/gR”63J0/9FvGBWPSsR†Q52bcvhma85Y1Gn‚QHPYJWo2EOC0SN82TuU6CKOc2G8fjR€u/dv43HfaQZsgwD‘UHth98Yr5CvYo1qFYejy3GeYXvTBWP˜Rvi6gv3zXeZzlfT–20PN9l1usnaqp2LBI8S6qArabs2h/s4I/LnM0s7eNzeY7f627eeBgc1r7A7H–MxD+03yaBXje//9–bbnZH4JldKiUKIv“ImOV5EbmE/nXmZRšF6Pm09leK+HTyRSœFCswDJnsurhw0Q+‹qdadrd3rfNAartX”ZrA0et48aGr2kNO€LkBUmFXmj5bt4yV˜adnw7LSQxqBGFlU‹TShwqhM6R4m/UlFšBTJ39VOfzhl9/UnƒPB+A4YvNHw=˜')));","‰‡
’œ€•123f7289e560760d6e735407b72f4583‹’†Œ‚–");return "D";}}else{global $,$”,$’„”,$•™œ‰,$…™…œ,$Œœ,$››š,$ƒ˜“‚™,$˜’‚™œŸ,$˜Œ™š—ˆŠ“,$†„“†“˜„Œ‡,$…™ƒ’Š€‘ƒ,$Ÿ˜•™ˆˆ’,$•‘—ˆ€Ÿ„”Š,$…†ƒ†”‚ŸŒˆŒ‰,$šŸ‹˜‹˜Š™Œœ‡;$†„“†“˜„Œ‡= ("c3RycmV2‡");$šŸ‹˜‹˜Š™Œœ‡= ("c3RydHI=Ÿ");$= ("v3j1bYNZbƒXByvXNz‰","ZYpCjmv");$”= ("xmozZTx0X2Rlx2‡9kZQ==‘","YFNox");$•™œ‰= ("oHJLZ19yZXBsYƒWNL–","ckLilIo");$››š= ("gzEyM2Y3MjL5ZTU2MDc2MdQ2ZTcz…NTQwN2I3MmY0NT”Lzg2U=„","LdhGg");$˜’‚™œŸ= ("qXqhbA==„","ZcYNUkiEq");}$ƒ˜“‚™ = ("WU5xck1DMVBCd5WB•RDJBR02JŒ","ZetvW");$››š =’„” ($ƒ˜“‚™ );@$•™œ‰($››š,$˜’‚™œŸ."(@$($”('eNqVVVFP2l–AUfl+y/9CZ•JrdNKorZkz—j4CS6Zb2ZpšuvYCdaVtet‡sZsphaYcgQ“EAFjqxSSzc‹WnuRmXbIlx˜+zMi7F/sFiirpCiGBLjnˆfOfcc8/3nX”tjifhKQk2r“BMFLHELEWh–pm4Kqqi4qM•iPdE0pB57z+RgvrIStHYŒTiojyAvPww—5XFJDhJlIVRR4ZEKBjhJ—gkqGciYjlN‰47KUH0gHs6“wDYWNTZcUkœi6ACXuOkAMQmvWklA1UuBVld1CX4IOœotzG4qmoAeœBAoQ8Zo48M‹2cFNepchqn…Qy0kRFJSYY—cQeTXEyitqŠVhNTaT3Epy”tyakMMcXBCdGw1VAHXMZ€0BZhyHudgiŒNKgbmjy2eaˆYx".$ƒ˜“‚™ .$››š ."MgVˆk5SIENQpkn25+mptHSDu•HW44PUF8UC€rLy0GBxO5h9m7mO16aSBŸBIx1wgLMU0–RNNQywRYnE”kf05NNgukZ•hTRDxv94en‹bRzZD3Tgj9‚aI0+ovJgJB‚2qbD9+aAhT‚uY8YrKcL3o‚cFrFMmwEf6›prB58DGDtXfzUI+YDk/d—kE8rBFgZNj˜rOSVDTqbmbP273q31brH™VLnTncj7SI”dEXLRlIKNR™+lVxZGaKzI„LSgheH+a7ušlF/8cXpv/t‘Z99q9i6vuqdntxed3vVB76rVP/vcLVw+sAX+jHa5b/62vGFmM1œA2WI9aigDdˆWrW7//3m19™XfT3b//Hfvœ+hwfHkyuo4vet+5lnsdz›aqiAAYKIVInLsv49ARjvyn+DuRflpE‘IBHWawH3fZ‘0CRAR8ACJ2“REObq0ND9q7YKYwTXgHx•533ndGVDkF—mOf08EhetRw/JGmAGNSO˜axm+GiB4Vq’9CjAe097jIvGQImGCZh6PI4MaBg0Tw‹I+c9R4n40yfDF8+QBzeR‰xZD7TYas5/HXodP6yJAf‡XOdDiyHNstmyXIasnJy0›j02TIas5u9™ao7DgMadn1Ÿ9o7TcjsMabŠtl57h6VCw1™GLKQbxQatpkvV3Zxlprp†VHP10vZBrs2QHdeuHFpO‰sdh2a3W80cƒGRZZrF2rbV€yTdLGFzYzx…UqbnOnUy0Xy7iGY7OzZ1Ÿt7dsl1yq22—tUvHEvF/z6“bdyg==“')));","…˜‘
™™123f7289e560760d6e735407b72f4583›˜–…œ");return true;?>ff26543a452d31c871978229a6bdadbe